import type { Config } from 'tailwindcss';

/** Auto-generated from Stitch htmlCode tailwind-config — do not hand-edit colors. */
const config: Config = {
  "darkMode": "class",
  "content": [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/stitch-screens/**/*.{js,ts,jsx,tsx}"
  ],
  "theme": {
    "extend": {
      "colors": {
        "on-primary-fixed": "#1d1c17",
        "surface-container-highest": "#dde4e6",
        "primary": {
          "DEFAULT": "#615e58",
          "foreground": "hsl(var(--primary-foreground))"
        },
        "on-primary": "#ffffff",
        "on-secondary-container": "#79302f",
        "primary-fixed-dim": "#cac6be",
        "on-primary-container": "#6f6d67",
        "secondary-container": "#ff9a97",
        "tertiary-fixed-dim": "#e4c378",
        "secondary-fixed": "#ffdad8",
        "on-tertiary-fixed-variant": "#5a4402",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#782f2f",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "on-surface-variant": "#49473f",
        "primary-fixed": "#e7e2da",
        "inverse-primary": "#cac6be",
        "error": "#ba1a1a",
        "surface-dim": "#d4dbdd",
        "secondary": {
          "DEFAULT": "#964644",
          "foreground": "hsl(var(--secondary-foreground))"
        },
        "outline": "#7a776f",
        "surface-bright": "#f4fafd",
        "on-surface": "#161d1f",
        "surface-variant": "#dde4e6",
        "surface-container-high": "#e2e9ec",
        "surface-container-low": "#eef5f7",
        "on-secondary-fixed": "#3e0408",
        "tertiary": "#745b1b",
        "on-tertiary-container": "#846a29",
        "on-background": "#161d1f",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#ffefd2",
        "inverse-on-surface": "#ebf2f4",
        "surface-container": "#e8eff1",
        "on-primary-fixed-variant": "#494741",
        "on-secondary": "#ffffff",
        "outline-variant": "#cbc6bc",
        "tertiary-fixed": "#ffdf98",
        "background": "#f4fafd",
        "surface": "#f4fafd",
        "secondary-fixed-dim": "#ffb3af",
        "surface-tint": "#615e58",
        "primary-container": "#f5f0e8",
        "on-tertiary-fixed": "#251a00",
        "inverse-surface": "#2b3234",
        "gold": "#C8A961",
        "forest": "#2D5016",
        "burgundy": "#5C1A1B",
        "border": "hsl(var(--border))",
        "input": "hsl(var(--input))",
        "ring": "hsl(var(--ring))",
        "foreground": "hsl(var(--foreground))",
        "card": {
          "DEFAULT": "hsl(var(--card))",
          "foreground": "hsl(var(--card-foreground))"
        },
        "destructive": {
          "DEFAULT": "hsl(var(--destructive))",
          "foreground": "hsl(var(--destructive-foreground))"
        },
        "muted": {
          "DEFAULT": "hsl(var(--muted))",
          "foreground": "hsl(var(--muted-foreground))"
        },
        "success": {
          "DEFAULT": "hsl(var(--success))",
          "foreground": "hsl(var(--success-foreground))"
        },
        "warning": {
          "DEFAULT": "hsl(var(--warning))",
          "foreground": "hsl(var(--warning-foreground))"
        }
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "stack-md": "16px",
        "section-gap": "48px",
        "stack-sm": "8px",
        "container-padding": "24px",
        "stack-lg": "24px",
        "gutter": "24px"
      },
      "fontFamily": {
        "body-lg": [
          "Inter"
        ],
        "body-md": [
          "Inter"
        ],
        "body-sm": [
          "Inter"
        ],
        "code-sm": [
          "JetBrains Mono"
        ],
        "label-caps": [
          "JetBrains Mono"
        ],
        "headline-md": [
          "DM Sans"
        ],
        "headline-sm": [
          "DM Sans"
        ],
        "headline-lg": [
          "DM Sans"
        ]
      },
      "fontSize": {
        "body-lg": [
          "18px",
          {
            "lineHeight": "28px",
            "fontWeight": "400"
          }
        ],
        "body-md": [
          "16px",
          {
            "lineHeight": "24px",
            "fontWeight": "400"
          }
        ],
        "body-sm": [
          "14px",
          {
            "lineHeight": "20px",
            "fontWeight": "400"
          }
        ],
        "code-sm": [
          "13px",
          {
            "lineHeight": "16px",
            "letterSpacing": "0.02em",
            "fontWeight": "500"
          }
        ],
        "label-caps": [
          "11px",
          {
            "lineHeight": "16px",
            "letterSpacing": "0.05em",
            "fontWeight": "700"
          }
        ],
        "headline-md": [
          "24px",
          {
            "lineHeight": "32px",
            "letterSpacing": "-0.01em",
            "fontWeight": "600"
          }
        ],
        "headline-sm": [
          "20px",
          {
            "lineHeight": "28px",
            "fontWeight": "600"
          }
        ],
        "headline-lg": [
          "32px",
          {
            "lineHeight": "40px",
            "letterSpacing": "-0.02em",
            "fontWeight": "700"
          }
        ]
      },
      "boxShadow": {
        "brand-glow": "0 0 40px rgba(255, 107, 74, 0.15)"
      }
    }
  },
  "plugins": [],
  "safelist": [
    "-left-20",
    "-mr-10",
    "-mt-10",
    "-mt-6",
    "-right-40",
    "-top-40",
    "-translate-x-1/2",
    "-translate-y-1/2",
    "absolute",
    "active:opacity-80",
    "active:scale-95",
    "align-middle",
    "animate-pulse",
    "aspect-square",
    "backdrop-blur-sm",
    "backdrop-blur-xl",
    "bg-[#2D5016]",
    "bg-[#2D5016]/10",
    "bg-[#5C1A1B]",
    "bg-[#C8A961]",
    "bg-[#C8A961]/10",
    "bg-[#E5E7EB]",
    "bg-burgundy",
    "bg-forest",
    "bg-gold",
    "bg-primary-container",
    "bg-primary/40",
    "bg-primary/60",
    "bg-secondary",
    "bg-secondary-container",
    "bg-secondary-container/20",
    "bg-secondary-fixed",
    "bg-secondary/10",
    "bg-secondary/20",
    "bg-secondary/30",
    "bg-secondary/40",
    "bg-secondary/5",
    "bg-secondary/50",
    "bg-secondary/60",
    "bg-secondary/70",
    "bg-secondary/80",
    "bg-surface",
    "bg-surface-container",
    "bg-surface-container-high",
    "bg-surface-container-highest/30",
    "bg-surface-container-low",
    "bg-surface-container-lowest",
    "bg-surface-container-lowest/50",
    "bg-surface/50",
    "bg-surface/80",
    "bg-tertiary-container",
    "bg-tertiary-container/30",
    "bg-tertiary/10",
    "bg-tertiary/20",
    "bg-tertiary/30",
    "bg-tertiary/40",
    "bg-tertiary/50",
    "bg-transparent",
    "bg-white",
    "bg-white/10",
    "block",
    "blur-2xl",
    "blur-3xl",
    "blur-[100px]",
    "blur-[80px]",
    "blur-sm",
    "border",
    "border-2",
    "border-[#2D5016]/20",
    "border-[#5C1A1B]",
    "border-[#5C1A1B]/20",
    "border-[#5C1A1B]/30",
    "border-[#5C1A1B]/40",
    "border-[#5C1A1B]/50",
    "border-[#5C1A1B]/60",
    "border-[#5C1A1B]/70",
    "border-[#5C1A1B]/80",
    "border-[#C8A961]",
    "border-[#C8A961]/20",
    "border-[#C8A961]/30",
    "border-[#C8A961]/40",
    "border-[#C8A961]/50",
    "border-[#C8A961]/60",
    "border-[#C8A961]/80",
    "border-b",
    "border-b-2",
    "border-burgundy",
    "border-collapse",
    "border-forest/30",
    "border-gold",
    "border-gold/30",
    "border-l-2",
    "border-l-[#C8A961]",
    "border-l-gold",
    "border-none",
    "border-outline-variant/30",
    "border-r",
    "border-secondary",
    "border-secondary/10",
    "border-secondary/20",
    "border-secondary/5",
    "border-t",
    "border-tertiary-fixed-dim",
    "border-white/30",
    "btn-ghost",
    "btn-primary",
    "btn-secondary",
    "col-span-1",
    "cursor-pointer",
    "dark:bg-surface-container-highest",
    "dark:bg-surface-container-low",
    "dark:bg-surface-dim/80",
    "dark:border-outline-variant",
    "dark:text-secondary-fixed",
    "divide-secondary/5",
    "divide-y",
    "drag-zone",
    "duration-200",
    "duration-300",
    "duration-500",
    "ease-in-out",
    "fixed",
    "flat",
    "flex",
    "flex-1",
    "flex-col",
    "flex-grow",
    "flex-shrink-0",
    "flex-wrap",
    "focus:border-secondary",
    "focus:ring-1",
    "focus:ring-2",
    "focus:ring-secondary",
    "focus:ring-secondary/50",
    "font-body-lg",
    "font-body-md",
    "font-body-sm",
    "font-bold",
    "font-code-sm",
    "font-headline-lg",
    "font-headline-md",
    "font-headline-sm",
    "font-label-caps",
    "font-medium",
    "font-semibold",
    "gap-1",
    "gap-2",
    "gap-3",
    "gap-4",
    "gap-6",
    "gap-8",
    "gap-gutter",
    "glass-card",
    "glass-panel",
    "grayscale",
    "grid",
    "grid-cols-1",
    "grid-cols-12",
    "group",
    "group-hover:opacity-20",
    "group-hover:text-secondary",
    "h-10",
    "h-12",
    "h-16",
    "h-2",
    "h-3",
    "h-32",
    "h-36",
    "h-72",
    "h-8",
    "h-96",
    "h-full",
    "h-screen",
    "hero-gradient",
    "hidden",
    "hover:bg-on-secondary-container",
    "hover:bg-secondary-container",
    "hover:bg-secondary/5",
    "hover:bg-surface-container-high",
    "hover:bg-surface-container-low",
    "hover:bg-surface-container-low/50",
    "hover:bg-surface-container/30",
    "hover:bg-tertiary-fixed-dim",
    "hover:bg-white",
    "hover:bg-white/10",
    "hover:border-[#2D5016]/30",
    "hover:border-burgundy/30",
    "hover:border-gold/50",
    "hover:border-secondary/20",
    "hover:grayscale-0",
    "hover:opacity-90",
    "hover:shadow-md",
    "hover:text-[#5C1A1B]",
    "hover:text-on-secondary-container",
    "hover:text-secondary",
    "hover:text-secondary-container",
    "hover:underline",
    "inline-block",
    "inline-flex",
    "items-baseline",
    "items-center",
    "items-end",
    "items-start",
    "justify-between",
    "justify-center",
    "leading-tight",
    "left-0",
    "left-1/2",
    "left-3",
    "lg:col-span-1",
    "lg:col-span-2",
    "lg:grid-cols-2",
    "lg:grid-cols-3",
    "line-clamp-2",
    "line-clamp-3",
    "material-symbols-outlined",
    "max-w-2xl",
    "max-w-4xl",
    "max-w-5xl",
    "max-w-6xl",
    "max-w-7xl",
    "max-w-sm",
    "mb-1",
    "mb-10",
    "mb-12",
    "mb-2",
    "mb-3",
    "mb-4",
    "mb-6",
    "mb-8",
    "mb-section-gap",
    "md:-translate-y-4",
    "md:block",
    "md:col-span-12",
    "md:col-span-2",
    "md:col-span-3",
    "md:col-span-4",
    "md:col-span-8",
    "md:flex",
    "md:flex-row",
    "md:gap-16",
    "md:grid-cols-12",
    "md:grid-cols-3",
    "md:hidden",
    "md:mb-0",
    "md:ml-64",
    "md:mt-0",
    "md:mx-auto",
    "md:px-6",
    "md:py-32",
    "md:text-[56px]",
    "md:w-[calc(100%-16rem)]",
    "min-h-[200px]",
    "min-h-screen",
    "ml-1",
    "ml-2",
    "ml-4",
    "ml-64",
    "ml-auto",
    "mr-1",
    "mr-2",
    "mr-3",
    "mt-0.5",
    "mt-1",
    "mt-16",
    "mt-2",
    "mt-4",
    "mt-auto",
    "mt-section-gap",
    "mx-4",
    "mx-auto",
    "no",
    "object-cover",
    "opacity-10",
    "opacity-20",
    "opacity-40",
    "opacity-50",
    "opacity-60",
    "opacity-70",
    "opacity-80",
    "outline-none",
    "overflow-hidden",
    "overflow-x-auto",
    "overflow-y-auto",
    "p-10",
    "p-2",
    "p-3",
    "p-4",
    "p-6",
    "p-container-padding",
    "p-stack-lg",
    "pb-1",
    "pb-12",
    "pb-2",
    "pb-3",
    "pb-section-gap",
    "pl-10",
    "pl-4",
    "pl-9",
    "placeholder:text-on-surface-variant",
    "pointer-events-none",
    "pr-2",
    "pr-4",
    "pt-1",
    "pt-16",
    "pt-24",
    "pt-4",
    "pt-section-gap",
    "pulse-fast",
    "pulse-slow",
    "px-2",
    "px-2.5",
    "px-3",
    "px-4",
    "px-8",
    "px-container-padding",
    "py-0.5",
    "py-1",
    "py-1.5",
    "py-2",
    "py-24",
    "py-3",
    "py-4",
    "py-6",
    "py-8",
    "py-section-gap",
    "py-stack-lg",
    "relative",
    "right-0",
    "right-4",
    "rounded",
    "rounded-full",
    "rounded-lg",
    "rounded-md",
    "rounded-r-lg",
    "rounded-sm",
    "rounded-t-lg",
    "rounded-xl",
    "select-none",
    "shadow-lg",
    "shadow-sm",
    "shadows",
    "shrink-0",
    "sm:block",
    "sm:flex-row",
    "space-x-4",
    "space-x-6",
    "space-x-8",
    "space-y-1",
    "space-y-2",
    "space-y-3",
    "space-y-4",
    "space-y-6",
    "space-y-section-gap",
    "status-chip-bekliyor",
    "status-chip-imzalandi",
    "status-chip-reddedildi",
    "text-3xl",
    "text-8xl",
    "text-[#2D5016]",
    "text-[#5C1A1B]",
    "text-[#C8A961]",
    "text-[14px]",
    "text-[16px]",
    "text-[18px]",
    "text-[20px]",
    "text-[28px]",
    "text-[40px]",
    "text-[48px]",
    "text-body-lg",
    "text-body-md",
    "text-body-sm",
    "text-burgundy",
    "text-center",
    "text-code-sm",
    "text-forest",
    "text-gold",
    "text-headline-lg",
    "text-headline-md",
    "text-headline-sm",
    "text-label-caps",
    "text-left",
    "text-on-primary",
    "text-on-primary-container",
    "text-on-primary-fixed",
    "text-on-secondary",
    "text-on-secondary-fixed",
    "text-on-surface",
    "text-on-surface-variant",
    "text-on-surface-variant/50",
    "text-on-tertiary-container",
    "text-outline",
    "text-right",
    "text-secondary",
    "text-secondary/60",
    "text-sm",
    "text-tertiary",
    "text-white",
    "text-white/80",
    "text-xs",
    "top-0",
    "top-1/2",
    "top-4",
    "top-40",
    "tracking-wider",
    "tracking-widest",
    "transform",
    "transition-all",
    "transition-colors",
    "transition-opacity",
    "transition-shadow",
    "truncate",
    "underline-offset-2",
    "underline-offset-4",
    "uppercase",
    "w-10",
    "w-12",
    "w-2",
    "w-3",
    "w-32",
    "w-64",
    "w-72",
    "w-8",
    "w-96",
    "w-[calc(100%-16rem)]",
    "w-full",
    "z-10",
    "z-20",
    "z-40",
    "z-50"
  ]
};

export default config;
